name: check_install

on:
  workflow_call:
    inputs:
      crate:
        required: true
        type: string

permissions: {}

jobs:
  install:
    name: Rust ${{matrix.rust}}${{matrix.locked && ', locked' || ''}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
        locked: [false, true]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo install ${{inputs.crate}} ${{matrix.locked && '--locked' || ''}}
