name: check_install

on:
  workflow_call:
    inputs:
      crate:
        required: true
        type: string

jobs:
  install:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo install ${{inputs.crate}}
