name: check_install

on:
  workflow_call:
    inputs:
      crate:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      crate:
        required: true
        type: string

permissions: {}

jobs:
  install:
    name: Rust ${{matrix.rust}}${{matrix.locked && ', locked' || ''}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, nightly]
        locked: [false, true]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - name: cargo install ${{inputs.crate}} ${{matrix.locked && '--locked' || ''}}
        run: cargo install ${{inputs.crate}} ${{matrix.locked && '--locked' || ''}} 2>&1 | tee ${{runner.temp}}/check_install.log
      - if: matrix.locked
        name: Check for yanked dependency
        run: |
          ! grep --quiet 'package `[^`]\+` in Cargo\.lock is yanked' ${{runner.temp}}/check_install.log
