name: Release

on: workflow_call

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine version from tag name
        id: vars
        run: echo version="${tag_name#v}" >> $GITHUB_OUTPUT
        env:
          tag_name: ${{github.event.release.tag_name}}
      - name: Package sources into tar.gz
        run: git archive ${{github.event.release.tag_name}} --prefix=${{github.event.repository.name}}-${{steps.vars.outputs.version}}/ --output=${{github.event.repository.name}}-${{steps.vars.outputs.version}}.tar.gz
      - name: Upload release archive
        run: gh release upload ${{github.event.release.tag_name}} ${{github.event.repository.name}}-${{steps.vars.outputs.version}}.tar.gz
        env:
          GH_TOKEN: ${{github.token}}
